Fix unreferenced variable error
If we can't get the gerrit patch in 4 tries, print an error instead of
this:

Traceback (most recent call last):
  File "/usr/local/google/home/seanpaul/s/review-o-matic/troll-o-matic.py", line 426, in <module>
    sys.exit(main())
  File "/usr/local/google/home/seanpaul/s/review-o-matic/troll-o-matic.py", line 423, in main
    troll.run()
  File "/usr/local/google/home/seanpaul/s/review-o-matic/troll-o-matic.py", line 394, in run
    did_review |= self.process_changes(p, changes)
  File "/usr/local/google/home/seanpaul/s/review-o-matic/troll-o-matic.py", line 298, in process_changes
    upstream_shas = rev.get_cherry_pick_shas_from_patch(gerrit_patch)
UnboundLocalError: local variable 'gerrit_patch' referenced before assignment

Signed-off-by: Sean Paul <seanpaul@chromium.org>